//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 06:14:26 PM CDT 
//


package com.task3.task4.unmarshall.marshall;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.task3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.task3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PurchaseOrderType }
     * 
     */
    public PurchaseOrderType createPurchaseOrderType() {
        return new PurchaseOrderType();
    }

    /**
     * Create an instance of {@link PurchaseOrderType.Items }
     * 
     */
    public PurchaseOrderType.Items createPurchaseOrderTypeItems() {
        return new PurchaseOrderType.Items();
    }

    /**
     * Create an instance of {@link PurchaseOrderType.ShipTo }
     * 
     */
    public PurchaseOrderType.ShipTo createPurchaseOrderTypeShipTo() {
        return new PurchaseOrderType.ShipTo();
    }

    /**
     * Create an instance of {@link PurchaseOrderType.BillTo }
     * 
     */
    public PurchaseOrderType.BillTo createPurchaseOrderTypeBillTo() {
        return new PurchaseOrderType.BillTo();
    }

    /**
     * Create an instance of {@link PurchaseOrderType.Items.Item }
     * 
     */
    public PurchaseOrderType.Items.Item createPurchaseOrderTypeItemsItem() {
        return new PurchaseOrderType.Items.Item();
    }

}
